#!/bin/bash
#
# To use this file simply type "./scrpt [file_to_be_plotted]"
# Example: If I want to plot the file named 20ccStats in gnuplot
#          and save it to a file with the same name with the .emf
#          extension, then I would type this in the command line:
#
#          ./scrpt 20ccStats
#
#          The output would be a file named 20ccStats.emf in the
#          current directory that is the graph of the plotted file

function gnu {
  var1=$1
  var1Emf=${1}.emf
  if [ "$2" != "" ]; then
    var2=$2
  else
    var2=gnuplotCmds2
  fi

  echo "plot \"$var1\"" > $var2
  echo "set term emf" >>  $var2
  echo "set output \"$var1Emf\"" >>  $var2
  echo "replot" >>  $var2
  echo "set term pop" >>  $var2
}

gnu $1 $2
gnuplot gnuplotCmds2
#rm gnuplotCmds2
